env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - GNAT_INSTALLER_PATH=$TOOLS_DIR/gnat-2020-20200818-x86_64-linux-bin
    - GNAT_PATH=$TOOLS_DIR/gnat-2020-x86_64-linux-bin

language: minimal

os:
  - linux

dist: focal

cache:
  directories:
  - $HOME/build_tools

before_install:
  - sudo apt-get update
  - sudo apt-get -y install wavbreaker

install: ./.travis/gnat_community_install.sh

jobs:
  include:
    - stage: "Verify generated source-code files"
      script:
        - PATH=$GNAT_PATH/bin:$PATH TEST=1 ./scripts/generate_src.sh
    - stage: "Build test for Wavefile Library"
      script:
        - PATH=$GNAT_PATH/bin:$PATH gprbuild -P test/wavefiles_test/wavefiles_test.gpr
    - stage: "Build & run Quick Wav-Data Check"
      script:
        - PATH=$GNAT_PATH/bin:$PATH gprbuild -P test/quick_wav_data_check/quick_wav_data_check.gpr && ./test/quick_wav_data_check/bin/quick_wav_data_check "$(date +"%Y%m%d-%H%M%S")_"
    - stage: "Build & check Cookbook"
      script:
        - PATH=$GNAT_PATH/bin:$PATH ./scripts/test_cookbook.sh
