env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - GNAT_INSTALLER_PATH=$TOOLS_DIR/gnat-2020-20200818-x86_64-linux-bin
    - GNAT_PATH=$TOOLS_DIR/gnat-2020-x86_64-linux-bin

language: julia
julia:
  - 1.4

os:
  - linux

dist: focal

cache:
  directories:
  - $HOME/build_tools

install: ./.travis/gnat_community_install.sh

jobs:
  include:
    - stage: "Verify generated source-code files"
      script:
        - PATH=$GNAT_PATH/bin:$PATH TEST=1 ./scripts/generate_src.sh
    - stage: "Build test for Wavefile Library"
      script:
        - PATH=$GNAT_PATH/bin:$PATH gprbuild -P test/wavefiles_test/wavefiles_test.gpr
