name: GNAT Community 2020 on macOS 10.15

on: [pull_request]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check cached GNAT toolchain
      uses: actions/cache@v2
      with:
        path: ./cached_gnat
        key: ${{ runner.os }}-gnat-ce-2020

    - name: Set up GNAT toolchain
      uses: ada-actions/toolchain@ce2020
      with:
        distrib: community
        target: native
        community_year: 2020
        install_dir: ./cached_gnat

    - name: Install dependencies
      run: . ./scripts/install_deps.sh

    - name: Verify generated source-code files
      run: TEST=1 ./scripts/generate_src.sh

    - name: Build test for Wavefile Library
      run: gprbuild -P test/wavefiles_test/wavefiles_test.gpr

    - name: Build Quick Wav-Data Check
      run: gprbuild -P test/quick_wav_data_check/quick_wav_data_check.gpr

    - name: Run Quick Wav-Data Check
      run: ./test/quick_wav_data_check/bin/quick_wav_data_check "$(date +"%Y%m%d-%H%M%S")_"
